using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;

namespace WebApplication1.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

public class PostCreateViewModel
{
    [Required]
    [MaxLength(256)]
    [Display(Name = "Title", Description = "Title of the post")]
    public string Title { get; set; }
    
    [Required]
    [MaxLength(256)]
    [Display(Name = "Slug", Description = "Title of the post")]
    public string Slug { get; set; }
    
    [Required]
    [MaxLength(2048)]
    [Display(Name = "Content", Description = "Content of the post")]
    public string Content { get; set; }
    
    [Display(Name = "Created at", Description = "Timestamp when the record was created (generated by the database)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime CreatedAt { get; set; }


    public List<int> SelectedTagIds { get; set; } = new List<int>();

    public PostCreateViewModel()
    {
        CreatedAt = DateTime.UtcNow;
    }
    
    public PostModel ToPostModel(string userId)
    {
        return new PostModel
        {
            Title = Title,
            Slug = Slug,
            Content = Content,
            AuthorId = userId,
            CreatedAt = CreatedAt,
            SelectedTagIds = SelectedTagIds
        };
    }
    
    
}