<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-LiveBlog-d31c42ec-0606-4f0e-9548-87fc8708b9c5</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.21"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.21"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.21"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="LiveBlog\Repositories\" />
      <Folder Include="LiveBlog\Services\" />
      <Folder Include="Repositories\" />
    </ItemGroup>

</Project>
